name: 'Setup Porter'
description: 'Install Porter to create and manage bundles'
branding:
  icon: user-check
  color: purple
runs:
  using: 'node20'
  main: 'index.js'
inputs:
  porter_version:
    description: 'Specify which version of Porter to install. Any version from v0.18.1-beta.2 onwards is valid. If left blank, will default to latest.'
    default: latest
    required: false
